<?php

namespace Icetig\Bundle\PedagoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Icetig\Bundle\UserBundle\Entity\Group;

/**
 * SanctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SanctionRepository extends EntityRepository
{
    public function getGroupSanctions(Group $group)
    {
        $qb = $this->_em->createQueryBuilder();

        $result = $qb->select('s')
            ->from('PedagoBundle:Sanction', 's')
            ->innerJoin('s.subject', 'u')
            ->innerJoin('u.groups', 'g')
            ->where('g = :group')
            ->setParameter('group', $group)
            ->getQuery()
            ->getResult();
        return $result;
    }
}
