# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Icetig\Bundle\ApiBundle\Controller\:
        resource: '../../src/Icetig/Bundle/ApiBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Icetig\Bundle\WebBundle\Controller\:
        resource: '../../src/Icetig/Bundle/WebBundle/Controller'
        public: true
        tags: ['controller.service_arguments']