api_security:
    prefix: /security
    resource: "@WebBundle/Resources/config/routing/api/security.yml"

api_user:
    prefix: /user
    resource: "@WebBundle/Resources/config/routing/api/user.yml"

api_permission:
    prefix: /permission
    resource: "@WebBundle/Resources/config/routing/api/permission.yml"

api_sanction:
    prefix: /sanction
    resource: "@WebBundle/Resources/config/routing/api/sanction.yml"

api_homepage:
    path: /
    defaults:
        _controller: ApiBundle:Default:index
