<?php

namespace Icetig\Bundle\ApiBundle\Repository;

use DateTime;
use DateInterval;
use Doctrine\ORM\EntityRepository;
use Icetig\Bundle\ApiBundle\Entity\Access;
use Icetig\Bundle\UserBundle\Entity\User;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends EntityRepository
{
    public function createNew(User $user, $expirationDelay = null)
    {
        if (null === $expirationDelay) {
            $expirationDelay = "PT20M";
        }

        $access = new Access();

        $expirationDate = new DateTime();
        $expirationDate->add(new DateInterval($expirationDelay));

        $access->setGenerationDate(new DateTime());
        $access->setExpirationDate($expirationDate);
        $access->setUser($user);

        return $access;
    }
}
